# -*- coding: utf-8 -*-
"""stage1+stage2야호.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1T1KIE4Bo9nWhhikDxWwwo9ux7NISC9

학습 데이터 Google Drive 마운트
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Stage1

## 1. 라이브러리 불러오기
"""

import csv
import json
import os

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.linear_model import LogisticRegression   #######윤서영
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split   #######윤서영 GridSearchCV, RandomizedSearchCV 추가
from sklearn.metrics import f1_score, classification_report   #######윤서영 classification_report 추가
import lightgbm as lgb   #######윤서영
import numpy as np   #######윤서영


# 예측 대상 14개 클래스 (Macro-F1 계산에 사용)
ALL_CLASSES = [
    "read_file", "grep_search", "list_directory", "glob_pattern",
    "edit_file", "write_file", "apply_patch",
    "run_bash", "run_tests", "lint_or_typecheck",
    "ask_user", "plan_task", "web_search", "respond_only",
]

"""##2. 데이터 불러오기


"""

DATA_DIR = "/content/drive/MyDrive/nlp_competition/data" ### 임유미 수정

# train.jsonl: 한 줄 = 샘플 하나
samples = [json.loads(line)
           for line in open(os.path.join(DATA_DIR, "train.jsonl"), encoding="utf-8")
           if line.strip()]

# train_labels.csv: id -> action 매핑
labels = {row["id"]: row["action"]
          for row in csv.DictReader(open(os.path.join(DATA_DIR, "train_labels.csv"), encoding="utf-8"))}

# 입력 X = current_prompt, 정답 y = action
X = [s["current_prompt"] for s in samples]
y = [labels[s["id"]] for s in samples]
ids = [s["id"] for s in samples]

print("samples:", len(X), "| classes:", len(set(y)))

"""##3. 학습 / 검증 데이터 분할"""

X_train, X_val, y_train, y_val, train_ids, val_ids = train_test_split(
    X, y, ids, test_size=0.2, stratify=y, random_state=42,
)
print("train:", len(X_train), "| val:", len(X_val))

"""##4. 모델 정의와 학습 (TF-IDF + LightGBM)"""

#1. TF-IDF
#단어(word) 단위 TF-IDF
word_vectorizer = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1, 2),
    max_features=60_000,
    sublinear_tf=True,
    lowercase=True,
)

#문자(char) 단위 TF-IDF
char_vectorizer = TfidfVectorizer(
    analyzer='char_wb',
    ngram_range=(2, 4),
    max_features=20_000,
    sublinear_tf=True,
    lowercase=True,
)

#둘을 FeatureUnion으로 결합
tfidf = FeatureUnion([
    ("word_tfidf", word_vectorizer),
    ("char_tfidf", char_vectorizer),
])

combined_vectorizer = tfidf

X_train_vec = combined_vectorizer.fit_transform(X_train)
X_val_vec = combined_vectorizer.transform(X_val)


#2. LightGBM
"""
param_grid = {
    "n_estimators": [300, 400],
    "num_leaves": [31, 50],
    "min_child_samples": [10, 20],
    "learning_rate": [0.05, 0.1],
}

clf = lgb.LGBMClassifier(objective="multiclass", class_weight="balanced", n_jobs=1, verbosity=1,random_state=42)
grid = RandomizedSearchCV(clf, param_grid, n_iter=8, scoring="f1_macro", cv=3, n_jobs=-1, verbose=2, random_state=42)
grid.fit(X_train_vec, y_train)

print("최적 파라미터:", grid.best_params_)"""

#1. TF-IDF
#단어(word) 단위 TF-IDF
word_vectorizer = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1, 2),
    max_features=60_000,
    sublinear_tf=True,
    lowercase=True,
)

#문자(char) 단위 TF-IDF
char_vectorizer = TfidfVectorizer(
    analyzer='char_wb',
    ngram_range=(2, 4),
    max_features=20_000,
    sublinear_tf=True,
    lowercase=True,
)

#둘을 FeatureUnion으로 결합
tfidf = FeatureUnion([
    ("word_tfidf", word_vectorizer),
    ("char_tfidf", char_vectorizer),
])

combined_vectorizer = tfidf

X_train_vec = combined_vectorizer.fit_transform(X_train)
X_val_vec = combined_vectorizer.transform(X_val)


#2. LightGBM
"""
param_grid = {
    "n_estimators": [300, 400],
    "num_leaves": [31, 50],
    "min_child_samples": [10, 20],
    "learning_rate": [0.05, 0.1],
}

clf = lgb.LGBMClassifier(objective="multiclass", class_weight="balanced", n_jobs=1, verbosity=1,random_state=42)
grid = RandomizedSearchCV(clf, param_grid, n_iter=8, scoring="f1_macro", cv=3, n_jobs=-1, verbose=2, random_state=42)
grid.fit(X_train_vec, y_train)

print("최적 파라미터:", grid.best_params_)"""

#LightGBM의 성능평가지표를 Macro-F1 직접 만들기

def macro_f1_eval(y_true, y_pred_proba):
    y_pred = y_pred_proba.reshape(len(y_true), -1).argmax(axis=1)
    f1 = f1_score(y_true, y_pred, average="macro")
    return "macro_f1", f1, True   # True = "높을수록 좋음"

#best_clf = lgb.LGBMClassifier(**grid.best_params_, objective="multiclass", class_weight="balanced", random_state=42)
clf = lgb.LGBMClassifier(n_estimators=2000, num_leaves=60, min_child_samples=10, learning_rate=0.1,
                               objective="multiclass", class_weight="balanced", random_state=42)
best_clf = clf

best_clf.fit(
    X_train_vec, y_train,
    eval_set=[(X_val_vec, y_val)],
    eval_metric=macro_f1_eval,
    callbacks=[lgb.early_stopping(stopping_rounds=200)],
)

"""### route_by_confidence"""

def route_by_confidence(ids, probs, classes, threshold=0.6): ### 임유미 수정 (인자로 classes를 받도록 함수 정의부 수정)


    """
    Stage1 예측 확률을 보고, 확신도에 따라 라우팅하는 함수

    Parameters
    ----------
    ids : list or array
        각 샘플의 고유 id (제출 포맷 맞추기 위해 필요)
    probs : np.ndarray, shape (샘플수, 14)
        best_clf.predict_proba(X_vec) 결과
    classes: probs의 각 컬럼이 어떤 클래스를 의미하는지 알려주는 배열
        (반드시 predict_proba를 만든 모델의 .classes_ 를 그대로 넘길 것) ### 임유미 추가
    threshold : float
        이 값 이상이면 Stage1에서 바로 확정

    Returns
    -------
    stage1_results : dict {id: action}
        확신도 높아서 Stage1에서 바로 결정된 것들
    stage2_input_ids : list
        확신도 낮아서 Stage2로 넘겨야 하는 id 목록
    stage2_probs : np.ndarray
        Stage2로 넘어가는 샘플들의 Stage1 확률 분포 (best_clf.predict_proba(X_vec) 결과)
    """
    max_conf = probs.max(axis=1)          # 각 샘플의 "가장 높은 확률"
    pred_idx = probs.argmax(axis=1)       # 그 확률에 해당하는 클래스 인덱스

    stage1_results = {}
    stage2_input_ids = []
    stage2_probs_list = []

    for sample_id, conf, idx, prob_row in zip(ids, max_conf, pred_idx, probs):
        if conf >= threshold:
            #확신도 높음 → 확정
            stage1_results[sample_id] = classes[idx]   ### 임유미: ALL_CLASSES → classes로 변경
        else:
            #확신도 낮음 → Stage2로
            stage2_input_ids.append(sample_id)
            stage2_probs_list.append(prob_row)

    stage2_probs = np.array(stage2_probs_list) if stage2_probs_list else np.empty((0, len(ALL_CLASSES)))

    return stage1_results, stage2_input_ids, stage2_probs

#stage2 들어갈 데이터 받는 예시 코드
probs = best_clf.predict_proba(X_val_vec)

stage1_results, stage2_input_ids, stage2_probs = route_by_confidence(
    ids=val_ids,
    probs=probs,
    classes=best_clf.classes_,   ### 임유미 추가
    threshold=0.7,
)

print(f"Stage1에서 확정된 샘플 수: {len(stage1_results)}")
print(f"Stage2로 넘어가는 샘플 수: {len(stage2_input_ids)}")

# 확정된 샘플들(Stage1에서 끝난 것들)만 따로 정확도 확인
stage1_conf_probs = best_clf.predict_proba(X_val_vec)
max_conf = stage1_conf_probs.max(axis=1)
pred = best_clf.predict(X_val_vec)

threshold = 0.7  # 사용 중인 임계값
confirmed_mask = max_conf >= threshold

confirmed_acc = (pred[confirmed_mask] == np.array(y_val)[confirmed_mask]).mean()
print(f"✅ 확정 샘플 수: {confirmed_mask.sum()}")
print(f"🎯 확정 샘플 중 정확도: {confirmed_acc:.4f}")

"""# 확신도 분포 히스토그램"""

import matplotlib.pyplot as plt

plt.hist(max_conf, bins=30)
plt.axvline(0.8, color='red', label='threshold=0.7 (current)')
plt.axvline(0.5, color='green', label='threshold=0.5 (candidate)')
plt.legend()
plt.title("Stage1 Confidence Distribution")
plt.xlabel("confidence")
plt.ylabel("sample count")
plt.show()

"""# 클래스별 확신도분포"""

import pandas as pd

df_check = pd.DataFrame({
    "true_label": y_val,
    "confidence": max_conf,
})

# write_file, respond_only만 따로 확신도 분포 확인
for cls in ["write_file", "respond_only"]:
    subset = df_check[df_check["true_label"] == cls]
    print(f"\n📌 {cls} (총 {len(subset)}건)")
    print(subset["confidence"].describe())
    print(f"  confidence >= 0.7 인 비율: {(subset['confidence'] >= 0.7).mean():.1%}")
    print(f"  confidence >= 0.5 인 비율: {(subset['confidence'] >= 0.5).mean():.1%}")

"""##5. 검증 (Macro-F1)"""

val_pred = best_clf.predict(X_val_vec)
macro_f1 = f1_score(y_val, val_pred, labels=ALL_CLASSES, average="macro", zero_division=0)
print(f"Validation Macro-F1: {macro_f1:.4f}")

"""클래스별 F1점수 보기"""

from sklearn.metrics import classification_report

print(classification_report(y_val, val_pred, labels=ALL_CLASSES, zero_division=0))

print("best_iteration_:", best_clf.best_iteration_)

"""#Stage2

## 1. 라이브러리 불러오기
"""

import pandas as pd

"""## 2. 데이터셋 구성"""

samples_by_id = {s["id"]: s for s in samples}

def build_stage2_input_text(sample, history_turns=3):
    """current_prompt + 최근 history 결합 (Stage1과 차별화 포인트)"""
    history = sample.get("history", []) or []
    hist_text = "\n".join(str(turn) for turn in history[-history_turns:])
    return f"{hist_text}\n{sample.get('current_prompt', '')}".strip()

def build_stage2_dataset(stage2_ids, stage2_probs, samples_by_id, labels, history_turns=3):
    """stage2_input_ids/stage2_probs(이미 순서 맞게 zip된 것) -> 텍스트/라벨/stage1확률 세트"""
    texts, y_stage2 = [], []
    for sid in stage2_ids:
        s = samples_by_id[sid]
        texts.append(build_stage2_input_text(s, history_turns))
        y_stage2.append(labels[sid])
    return texts, y_stage2, np.array(stage2_probs)

X_stage2_text, y_stage2, stage1_probs_stage2 = build_stage2_dataset(
    stage2_input_ids, stage2_probs, samples_by_id, labels,
)
print(f"Stage2 학습 후보: {len(X_stage2_text)}건")
print(pd.Series(y_stage2).value_counts())  # 클래스별 분포 체크 — 너무 적은 클래스 있는지 확인

"""## 3. 분류 헤드(현재: MiniLM 임베딩 + Logistic 헤드)

"""

from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression

# Stage2 내부 자체 train/val 분할 (1.2.2 디버깅용 지표 뽑으려고)
X_s2_train, X_s2_val, y_s2_train, y_s2_val, p_s2_train, p_s2_val = train_test_split(
    X_stage2_text, y_stage2, stage1_probs_stage2,
    test_size=0.2, stratify=y_stage2, random_state=42,
)

embedder = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")  # freeze, 학습 안 함
emb_train = embedder.encode(X_s2_train, show_progress_bar=True)
emb_val = embedder.encode(X_s2_val, show_progress_bar=True)

# Stage1의 14차원 확률도 같이 붙이기 (버리기 아까운 정보)
feat_train = np.hstack([emb_train, p_s2_train])
feat_val = np.hstack([emb_val, p_s2_val])

head = LogisticRegression(max_iter=1000, class_weight="balanced")
head.fit(feat_train, y_s2_train)

"""## 4. Macro-F1 측정(stage2 단독, 디버깅용)"""

pred_s2_val = head.predict(feat_val)
stage2_macro_f1 = f1_score(y_s2_val, pred_s2_val, labels=ALL_CLASSES, average="macro", zero_division=0)
print(f"Stage2 단독 Validation Macro-F1: {stage2_macro_f1:.4f}")
print(classification_report(y_s2_val, pred_s2_val, labels=ALL_CLASSES, zero_division=0))

"""# 최종 파이프라인 Macro-F1 측정"""

# ============================================================
# 최종 파이프라인 Macro-F1 (Stage1 확정 + Stage2 예측을 합쳐서 val 전체 기준 재채점)
#
# 주의: head는 X_s2_train(stage2 데이터의 80%)으로 학습됐기 때문에,
# 그 부분에 대한 예측은 약간의 낙관적 편향(leakage)이 있을 수 있음.
# 정확한 홀드아웃 검증을 원하면 cross_val_predict로 다시 뽑아야 하지만,
# 지금은 파이프라인이 실제로 어느 정도 나오는지 "근사치 확인" 목적.
# ============================================================

# ---- 1. Stage2로 넘어간 전체 샘플에 대해 head로 예측 ----
emb_stage2_all = embedder.encode(X_stage2_text, show_progress_bar=True)
feat_stage2_all = np.hstack([emb_stage2_all, stage1_probs_stage2])

stage2_preds_all = head.predict(feat_stage2_all)

# id -> stage2 예측 매핑
stage2_pred_map = dict(zip(stage2_input_ids, stage2_preds_all))

# ---- 2. Stage1 확정 결과(stage1_results) + Stage2 예측을 합쳐서 val 전체 예측 구성 ----
final_pipeline_preds = []
for vid in val_ids:
    if vid in stage1_results:
        final_pipeline_preds.append(stage1_results[vid])      # Stage1에서 확정된 것
    else:
        final_pipeline_preds.append(stage2_pred_map[vid])      # Stage2가 예측한 것

# ---- 3. val 전체(y_val) 기준으로 최종 Macro-F1 계산 ----
final_macro_f1 = f1_score(
    y_val, final_pipeline_preds, labels=ALL_CLASSES, average="macro", zero_division=0,
)
print(f"🎯 최종 파이프라인 Macro-F1 (val 전체 14,000건 기준): {final_macro_f1:.4f}")
print()
print(classification_report(y_val, final_pipeline_preds, labels=ALL_CLASSES, zero_division=0))

"""# Threshold 스윕

"""

# ============================================================
# Threshold 스윕: 여러 threshold 값으로 전체 파이프라인을 반복 실행해서
# 최종 Macro-F1을 비교하는 코드
#
# 주의: 이 셀은 threshold 하나당 MiniLM 임베딩을 다시 계산하고 head도
# 다시 학습하기 때문에 시간이 좀 걸림 (threshold 개수 x head 학습 1회씩)
# ============================================================

thresholds_to_try = [0.4, 0.5, 0.6, 0.7, 0.8]
sweep_results = []

# Stage1 확률은 threshold와 무관하게 고정된 값이므로 미리 한 번만 계산
val_probs = best_clf.predict_proba(X_val_vec)

for th in thresholds_to_try:
    print(f"\n{'='*50}")
    print(f"threshold = {th}")
    print(f"{'='*50}")

    # ① 라우팅
    stage1_results_th, stage2_ids_th, stage2_probs_th = route_by_confidence(
        ids=val_ids, probs=val_probs, classes=best_clf.classes_, threshold=th,
    )

    # 극단적으로 한쪽으로 다 쏠리면(Stage2 후보가 너무 적으면) 학습이 불안정하니 건너뜀
    if len(stage2_ids_th) < 50:
        print(f"  ⚠️ Stage2 후보가 {len(stage2_ids_th)}건뿐이라 건너뜀")
        continue

    # ② Stage2 데이터셋 구성
    X_text_th, y_th, probs_stage2_th = build_stage2_dataset(
        stage2_ids_th, stage2_probs_th, samples_by_id, labels,
    )

    # ③ head 학습 (전체 Stage2 후보로 바로 학습 — 스윕 단계에서는 별도 val 분할 없이 전체로)
    emb_th = embedder.encode(X_text_th, show_progress_bar=False)
    feat_th = np.hstack([emb_th, probs_stage2_th])

    head_th = LogisticRegression(max_iter=1000, class_weight="balanced")
    head_th.fit(feat_th, y_th)

    # ④ Stage2 예측 (같은 데이터로 예측하는 거라 약간 낙관적 - 순위 비교용 근사치)
    stage2_preds_th = head_th.predict(feat_th)
    stage2_pred_map_th = dict(zip(stage2_ids_th, stage2_preds_th))

    # ⑤ 최종 파이프라인 예측 병합
    final_preds_th = []
    for vid in val_ids:
        if vid in stage1_results_th:
            final_preds_th.append(stage1_results_th[vid])
        else:
            final_preds_th.append(stage2_pred_map_th[vid])

    # ⑥ 최종 Macro-F1
    macro_f1_th = f1_score(y_val, final_preds_th, labels=ALL_CLASSES, average="macro", zero_division=0)

    print(f"  Stage1 확정: {len(stage1_results_th)}건 | Stage2행: {len(stage2_ids_th)}건")
    print(f"  최종 파이프라인 Macro-F1: {macro_f1_th:.4f}")

    sweep_results.append({
        "threshold": th,
        "stage1_confirmed": len(stage1_results_th),
        "stage2_count": len(stage2_ids_th),
        "final_macro_f1": macro_f1_th,
    })

# ---- 결과 표로 정리 ----
sweep_df = pd.DataFrame(sweep_results)
print("\n" + "="*50)
print("Threshold 스윕 결과 요약")
print("="*50)
print(sweep_df.to_string(index=False))

"""# F1-속도 트레이드 오프 확인"""

import time
start = time.time()
_ = embedder.encode(X_stage2_text, show_progress_bar=False)
elapsed = time.time() - start
print(f"{len(X_stage2_text)}건 인코딩 소요 시간: {elapsed:.1f}초")
print(f"건당 평균: {elapsed/len(X_stage2_text)*1000:.2f}ms")

"""# 최종 재학습&저장
## 전체 데이터로 재학습 & 모델 저장

"""

# 전체 학습 데이터로 재학습
tfidf_final = tfidf
X_full_vec = tfidf_final.fit_transform(X)

clf_final = clf
clf_final.fit(X_full_vec, y)

# 저장 (추론용 script.py가 ./model/tfidf_lgbm.pkl 을 불러옵니다)
os.makedirs("./model", exist_ok=True)
joblib.dump(clf_final, "./model/tfidf_lgbm.pkl", compress=3)
print("저장 완료: ./model/tfidf_lgbm.pkl")

emb_all = embedder.encode(X_stage2_text, show_progress_bar=True)
feat_all = np.hstack([emb_all, stage1_probs_stage2])

final_head = LogisticRegression(max_iter=1000, class_weight="balanced")
final_head.fit(feat_all, y_stage2)

os.makedirs("./model", exist_ok=True)
joblib.dump(
    {"embedder_name": "paraphrase-multilingual-MiniLM-L12-v2", "head": final_head, "use_stage1_probs": True},
    "./model/stage2_minilm_head.pkl", compress=3,
)
print("저장 완료: ./model/stage2_minilm_head.pkl")